// Teste
export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const LOADING_USER = 'LOADING_USER'
export const USER_LOADED = 'USER_LOADED'
export const SET_POSTS = 'SET_POSTS'
export const CREATING_POST = 'CREATING_POST'
export const POST_CREATED = 'POST_CREATED'
export const ADD_COMMENT = 'ADD_COMMENT'

// Login Eduno
export const LOADING_USER_EDUNO = 'LOADING_USER_EDUNO'
export const USER_LOADED_EDUNO = 'USER_LOADED_EDUNO'
export const USER_LOGGED_IN_EDUNO = 'USER_LOGGED_IN_EDUNO'
export const USER_LOGGED_OUT_EDUNO = 'USER_LOGGED_OUT_EDUNO'
export const ATUALIZA_ID = 'ATUALIZA_ID'

// Perfil
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_INICIO = 'SET_INICIO'
export const LOADING_INICIO = 'LOADING_INICIO'
export const INICIO_LOADED = 'INICIO_LOADED'

// Noticias
export const SET_NOTICIAS = 'SET_NOTICIAS'
export const SET_NOTICIA_DETALHADA = 'SET_NOTICIA_DETALHADA'

// Boletim
export const SET_ETAPA = 'SET_ETAPA'
export const ATUALIZA_ETAPA = 'ATUALIZA_ETAPA'

// Eventos
export const SET_EVENTOS = 'SET_EVENTOS'
export const ATUALIZA_EVENTOS = 'ATUALIZA_EVENTOS'

// Tarefas
export const SET_TAREFAS = 'SET_TAREFAS'
export const SET_TAREFA_DETALHADA = 'SET_TAREFA_DETALHADA'
export const ATUALIZA_ETAPA_TAREFA = 'ATUALIZA_ETAPA_TAREFA'

// Horarios
export const SET_HORARIOS = 'SET_HORARIOS'
export const ATUALIZA_HORARIOS = 'ATUALIZA_HORARIOS'

// Provas
export const SET_PROVAS = 'SET_PROVAS'
export const ATUALIZA_PROVAS = 'ATUALIZA_PROVAS'

// Menu Principal
